# Generated by Django 4.2.7 on 2025-08-17 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_resumes', models.IntegerField(default=0)),
                ('new_resumes', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('total_analyses', models.IntegerField(default=0)),
                ('total_recommendations', models.IntegerField(default=0)),
                ('new_recommendations', models.IntegerField(default=0)),
                ('total_courses', models.IntegerField(default=0)),
                ('total_bookmarks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_resumes', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('total_analyses', models.IntegerField(default=0)),
                ('total_skills_identified', models.IntegerField(default=0)),
                ('total_skill_gaps', models.IntegerField(default=0)),
                ('total_recommendations_received', models.IntegerField(default=0)),
                ('total_courses_bookmarked', models.IntegerField(default=0)),
                ('total_courses_started', models.IntegerField(default=0)),
                ('total_courses_completed', models.IntegerField(default=0)),
                ('total_logins', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('streak_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('resume_upload', 'Resume Upload'), ('resume_convert', 'Resume Convert'), ('resume_analyze', 'Resume Analyze'), ('skill_analysis', 'Skill Analysis'), ('view_recommendations', 'View Recommendations'), ('bookmark_course', 'Bookmark Course'), ('start_course', 'Start Course'), ('complete_course', 'Complete Course')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='dashboard_u_user_id_5150cc_idx'), models.Index(fields=['created_at'], name='dashboard_u_created_8f7e1e_idx')],
            },
        ),
    ]
