# Generated by Django 4.2.7 on 2025-08-17 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('resume_type', models.CharField(choices=[('uploaded', 'Uploaded'), ('generated', 'AI Generated'), ('converted', 'Text Converted')], max_length=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='resumes/original/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='resumes/processed/')),
                ('original_text', models.TextField(blank=True)),
                ('processed_content', models.JSONField(default=dict)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('achievements', models.JSONField(default=list)),
                ('skills_used', models.JSONField(default=list)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='resumes.resume')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.JSONField(default=list)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resumes.resume')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('achievements', models.JSONField(default=list)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resumes.resume')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('personal_info', 'Personal Information'), ('summary', 'Professional Summary'), ('experience', 'Work Experience'), ('education', 'Education'), ('skills', 'Skills'), ('projects', 'Projects'), ('certifications', 'Certifications'), ('languages', 'Languages'), ('awards', 'Awards'), ('references', 'References')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resumes.resume')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('resume', 'section_type')},
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', '-created_at'], name='resumes_res_user_id_6019d7_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['status'], name='resumes_res_status_dd2fd3_idx'),
        ),
    ]
